## Info endpoint
info:
  app:
    name: Admin server
    description: Admin Server

server:
  port: ${PORT:9998}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry.credentials.uri:http://localhost:8761}/eureka/
 
management:
  security: 
    enabled: true


---
spring:
  profiles: docker
 

eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
